name: 'ci'

on:
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for TiDB Serverless branch to be ready
      uses: tidbcloud/wait-for-tidbcloud-branch@v0
      id: wait-for-branch
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        public-key: ${{ secrets.TIDB_CLOUD_API_PUBLIC_KEY }}
        private-key: ${{ secrets.TIDB_CLOUD_API_PRIVATE_KEY }}

    - name: Test with TiDB Serverless branch
      run: |
          echo "The host is ${{ steps.wait-for-branch.outputs.host }}"
          echo "The user is ${{ steps.wait-for-branch.outputs.user }}"
          echo "The password is ${{ steps.wait-for-branch.outputs.password }}"